#!/usr/bin/env python

import os, sys

fb = open('input1.txt', 'r')

text = fb.read().split('\n')[:-1]


count = { 1 : 0, 2 : 0, 3 : 0 }

for i in range(len(text[:])):
    text[i] = int(text[i])

text.append(0)
text.append(max(text)+3)
text.sort()

for i in range(len(text[:]) - 1):
    diff = text[i + 1] - text[i]
    count[diff] = count[diff] + 1


# print(text)
print(count[1] * count[3])

MAX_LIST = max(text)

DP = {}

def rec_count(list, num):

    if num == MAX_LIST:
        return 1

    if num in DP:
        return DP[num]

    count = 0

    if (num + 1 in list):
        count = count + rec_count(list, num+1)

    if (num + 2 in list):
        count = count + rec_count(list, num+2)

    if (num + 3 in list):
        count = count + rec_count(list, num+3)

    DP[num] = count
    return count

print(rec_count(text, 0))
