#!/usr/bin/env python

import os, sys

fb = open('input.txt', 'r')

text = fb.read().split('\n')[:-1]

# print(text)

# Part one

print("Part one:")

for i in text:
    for j in text:
        if i == j:
            pass
        if int(i) + int(j) == 2020:
            print(i)
            print(j)
            print(int(i)*int(j))
            break
    else:
        continue
    break

# Part two

print("Part two:")

for i in text:
    for j in text:
        for k in text:
            if i == j or j == k or k == i:
                pass
            if int(i) + int(j) + int(k) == 2020:
                print(i)
                print(j)
                print(k)
                print(int(i)*int(j)*int(k))
                break
        else:
            continue
        break
    else:
        continue
    break
