#!/usr/bin/env python

import os, sys

fb = open('input.txt', 'r')

text = fb.read().split('\n')[:-1]

for i in range(len(text[:])):
    text[i] = text[i].split(" ")
    text[i][0] = text[i][0].split('-')

# Part One

count = 0

for i in range(len(text[:])):
    curr_count = text[i][2].count(text[i][1][0])
    if (int(text[i][0][0]) <= curr_count and curr_count <= int(text[i][0][1])):
        count = count + 1

print(len(text))
print(count)

# Part Two

count = 0

for i in range(len(text[:])):
    if ((text[i][2][int(text[i][0][0]) - 1]) == text[i][1][0] or
        (text[i][2][int(text[i][0][1]) - 1]) == text[i][1][0]):
        if ((text[i][2][int(text[i][0][0]) - 1]) !=
            (text[i][2][int(text[i][0][1]) - 1])):
            count = count + 1

print(count)
