#!/usr/bin/env python

import os, sys

fb = open('input1.txt', 'r')

text = fb.read().split('\n')[:-1]

# print(text)

PAST_LEN = 25

def find_sum(list, number):
    # print(list)
    for i in range(len(list)):
        for j in range(len(list)):
            if i != j:
                if list[i] + list[j] == number:
                    return True, [list[i], list[j]]
                # else:
                #     print(list[i], " + ", list[j], " != ", number)

    return False, []

def find_sum_range(list, number):
    for i in range(len(list)):
        for j in range(len(list)):
            if sum(list[i:j]) == number:
                return True, [min(list[i:j]), max(list[i:j])]

    return False, []

for number in range(len(text[:])):
    text[number] = int(text[number])

odd = 0

for id in range(len(text[:])):
    if id > PAST_LEN - 1:
        found, ints = find_sum(text[id-PAST_LEN:id], text[id])
        if found:
            # print(ints[0], " + ", ints[1], " = ", text[id])
            pass
        else:
            odd = text[id]
            print(text[id], " is the odd one out")
    # else:
    #     print(text[id], " is in beginning")

found2, ints = find_sum_range(text, odd)

if found2:
    print("sum of nums from ", ints[0], " + ",  ints[1], " = ",  ints[0] +  ints[1])
    print(ints[0], " ", ints[1])
